### ISSUE TITLE
https://i.imgur.com/dCiq8TA.png

### ISSUE THREAD

**Issue by hueldoeu** [bouletmarc/TeamViewer_IDReset#2]
https://i.imgur.com/dCiq8TA.png
nice try FBI
![dCiq8TA](https://user-images.githubusercontent.com/11273667/236636255-aed9d71d-1fee-4a50-88d6-cabc1c3ec81a.png)

**Comment by bouletmarc** [comment]
dude this is a cracking/hacking tool, obviously it will be detected by 'antivirus' which as antipiracy measures in them. If you dont trust cracked tools then dont look forward them because obviously they'll all be detected somehow and surely.

**Comment by hueldoeu** [comment]
> dude this is a cracking/hacking tool, obviously it will be detected by 'antivirus' which as antipiracy measures in them. If you dont trust cracked tools then dont look forward them because obviously they'll all be detected somehow and surely.

i used this and can continue my work
https://www.youtube.com/watch?v=Ar7Isj0zJWE
![Screenshot 2023-05-07 202346](https://user-images.githubusercontent.com/11273667/236695659-cad66013-9fdc-4281-9e28-c5063cc1ecb3.png)

[TVTools_AlterID.zip](https://github.com/bouletmarc/TeamViewer_IDReset/files/11415709/TVTools_AlterID.zip)
